# Generated by Django 5.2.5 on 2025-08-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vital_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='myapp.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
