# Generated by Django 5.2.5 on 2025-08-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('sig', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('refills', models.CharField(max_length=255)),
                ('days', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='myapp.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
